name: Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
      
      - name: Print current working directory
        run: pwd
      
      - name: List contents of upload directory
        run: ls -la upload
      
      - name: Authenticate to Google Drive
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Print access token
        run: echo ${{ secrets.GDRIVE_ACCESS_TOKEN }}
      
      - name: Verify authentication and access to Google Drive
        run: |
          python -c "
          from google.oauth2.credentials import Credentials
          from googleapiclient.errors import HttpError
          from googleapiclient.discovery import build

          try:
              creds = Credentials.from_authorized_user_info(info=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }})
              drive = build('drive', 'v3', credentials=creds)
              files = drive.files().list().execute()
              print(f'Successfully authenticated and accessed Google Drive. Number of files: {len(files["files"])}')
          except HttpError as error:
              print(f'Failed to authenticate/access Google Drive: {error}')
          "
      
      - name: Upload files to Google Drive
        run: |
          cd upload
          for file in *; do
            if [[ -f "$file" ]]; then
              echo "Uploading $file to Google Drive..."
              FILE_ID=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.GDRIVE_ACCESS_TOKEN }}" -H "Content-Type: application/json" -d "{\"name\":\"$file\"}" "https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable" | grep -i "location" | sed -e "s/.*=//g" | tr -d '[:space:]')
              curl -s -X POST -L --retry 3 --retry-delay 5 --retry-max-time 120 --data-binary "@$file" -H "Content-Type: application/octet-stream" -H "Authorization: Bearer ${{ secrets.GDRIVE_ACCESS_TOKEN }}" -H "Content-Length: $(stat -c%s "$file")" -H "X-Upload-Content-Type: $(file -b --mime-type $file)" -H "X-Upload-Content-Length: $(stat -c%s "$file")" -H "Session-ID: 1" -H "Content-Range: bytes 0-$(stat -c%s "$file")/$(stat -c%s "$file")" -H "Expect: " "$FILE_ID"
              echo "Uploaded $file to Google Drive!"
            fi
          done
