name: Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Authenticate to Google Drive
        id: auth
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Verify authentication to Google Drive
        run: |
          python -c 'from google.oauth2.credentials import Credentials; creds = Credentials.from_authorized_user_info(info=${{ steps.auth.outputs.credentials }}); print(f"Successfully authenticated to Google Drive as {creds.valid_email}")'
      
      - name: Authorize access to Google Drive
        id: auth_drive
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          authorization_scope: https://www.googleapis.com/auth/drive
      
      - name: Verify authorization to Google Drive
        run: |
          python -c 'from google.oauth2.credentials import Credentials; creds = Credentials.from_authorized_user_info(info=${{ steps.auth_drive.outputs.credentials }}); print(f"Successfully authorized access to Google Drive as {creds.valid_email}")'
      
      - name: Access Google Drive
        run: |
          python -c 'from google.oauth2.credentials import Credentials; from googleapiclient.discovery import build; creds = Credentials.from_authorized_user_info(info=${{ steps.auth_drive.outputs.credentials }}); drive = build("drive", "v3", credentials=creds); files = drive.files().list().execute(); print(f"Successfully accessed Google Drive. Number of files: {len(files.get("files", []))}")'

      - name: Upload files to Google Drive
        run: |
          cd upload
          for file in *; do
            if [[ -f "$file" ]]; then
              echo "Uploading $file to Google Drive..."
              FILE_ID=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.GDRIVE_ACCESS_TOKEN }}" -H "Content-Type: application/json" -d "{\"name\":\"$file\"}" "https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable" | grep -i "location" | sed -e "s/.*=//g" | tr -d '[:space:]')
              curl -s -X POST -L --retry 3 --retry-delay 5 --retry-max-time 120 --data-binary "@$file" -H "Content-Type: application/octet-stream" -H "Authorization: Bearer ${{ secrets.GDRIVE_ACCESS_TOKEN }}" -H "Content-Length: $(stat -c%s "$file")" -H "X-Upload-Content-Type: $(file -b --mime-type $file)" -H "X-Upload-Content-Length: $(stat -c%s "$file")" -H "Session-ID: 1" -H "Content-Range: bytes 0-$(stat -c%s "$file")/$(stat -c%s "$file")" -H "Expect: " "$FILE_ID"
              echo "Uploaded $file to Google Drive!"
            fi
          done
