name: Upload to Google Drive

on:
  push:
    paths:
      - 'upload/**'

env:
  FOLDER_ID: your_folder_id_here
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload to Google Drive
      uses: adityak74/google-drive-upload-git-action@v0.3
      with:
        src: 'upload'
        dest: '/'
        service_account_email: ${{ env.SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
        folder_id: ${{ env.FOLDER_ID }}
