name: Upload to Google Drive

on:
  push:
    paths:
      - 'upload/**'
  workflow_dispatch:

env:
  FOLDER_ID: 1TOEfp9KAzh5gldWkX9LdJBS_xScXOTPk
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Input file name
      id: filename
      run: echo "::set-output name=filename::$(basename upload/*)"
    - name: Upload to Google Drive
      uses: adityak74/google-drive-upload-git-action@v0.3
      with:
        filename: ${{ steps.filename.outputs.filename }}
        service_account_email: ${{ env.SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}
        folderId: ${{ env.FOLDER_ID }}
