name: Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Authenticate to Google Drive
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Verify authentication to Google Drive
        run: |
          python -c 'from google.oauth2.credentials import Credentials; creds = Credentials.from_authorized_user_info(info=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}); print(f"Successfully authenticated to Google Drive as {creds.valid_email}")'
      
      - name: Upload files to Google Drive
        run: |
          cd upload
          for file in *; do
            if [[ -f "$file" ]]; then
              echo "Uploading $file to Google Drive..."
              FILE_ID=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.GDRIVE_ACCESS_TOKEN }}" -H "Content-Type: application/json" -d "{\"name\":\"$file\"}" "https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable" | grep -i "location" | sed -e "s/.*=//g" | tr -d '[:space:]')
              curl -s -X POST -L --retry 3 --retry-delay 5 --retry-max-time 120 --data-binary "@$file" -H "Content-Type: application/octet-stream" -H "Authorization: Bearer ${{ secrets.GDRIVE_ACCESS_TOKEN }}" -H "Content-Length: $(stat -c%s "$file")" -H "X-Upload-Content-Type: $(file -b --mime-type $file)" -H "X-Upload-Content-Length: $(stat -c%s "$file")" -H "Session-ID: 1" -H "Content-Range: bytes 0-$(stat -c%s "$file")/$(stat -c%s "$file")" -H "Expect: " "$FILE_ID"
              echo "Uploaded $file to Google Drive!"
            fi
          done
      
      - name: Verify upload to Google Drive
        run: |
          python -c 'import os; from google.oauth2.credentials import Credentials; from googleapiclient.discovery import build; creds = Credentials.from_authorized_user_info(info=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}); drive = build("drive", "v3", credentials=creds); query = f"name=\'{os.environ['GITHUB_REPOSITORY'].split('/')[1]}\' and mimeType=\'application/vnd.google-apps.folder\' and trashed=false"; folders = drive.files().list(q=query).execute().get("files"); assert len(folders) == 1, f"Expected 1 folder, got {len(folders)}"; folder_id = folders[0]['id']; files = drive.files().list(q=f"parents=\'{folder_id}\' and trashed=false").execute().get("files"); assert len(files) > 0, "No files found in the target folder"'
