name: Upload to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Authenticate to Google Drive
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Verify authentication
        run: |
          python -c 'from google.oauth2.credentials import Credentials; creds = Credentials.from_authorized_user_info(info='${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'); print(f"Successfully authenticated to Google Drive as {creds.valid_email}")'
      
      - name: Upload files to Google Drive
        run: |
          cd upload
          for file in *; do
            if [[ -f "$file" ]]; then
              echo "Uploading $file to Google Drive..."
              FILE_ID=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.GDRIVE_ACCESS_TOKEN }}" -H "Content-Type: application/json" -d "{\"name\":\"$file\"}" "https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable" | grep -i "location" | sed -e "s/.*=//g" | tr -d '[:space:]')
              echo "Created upload session for $file with ID $FILE_ID"
              curl -s -X POST -L --retry 3 --retry-delay 5 --retry-max-time 120 --data-binary "@$file" -H "Content-Type: application/octet-stream" -H "Authorization: Bearer ${{ secrets.GDRIVE_ACCESS_TOKEN }}" -H "Content-Length: $(stat -c%s "$file")" -H "X-Upload-Content-Type: $(file -b --mime-type $file)" -H "X-Upload-Content-Length: $(stat -c%s "$file")" -H "Session-ID: 1" -H "Content-Range: bytes 0-$(stat -c%s "$file")/$(stat -c%s "$file")" -H "Expect: " "$FILE_ID"
              echo "Uploaded $file to Google Drive!"
            fi
          done
      
      - name: Verify upload
        run: |
          python -c 'import google.auth, google.auth.transport.requests, google.oauth2.credentials, googleapiclient.errors; creds = google.oauth2.credentials.Credentials.from_authorized_user_info(info='${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'); service = googleapiclient.discovery.build("drive", "v3", credentials=creds); files = service.files().list(fields="files(name)").execute(); file_names = [file["name"] for file in files["files"]]; uploaded_files = set(file_names) & set(os.listdir("upload")); assert len(uploaded_files) == len(os.listdir("upload")), "Not all files were uploaded to Google Drive"'
