name: Test Google Drive Connection

on: [push]

jobs:
  test_connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: githubtodrive
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: List files in Google Drive
        run: |
          gcloud drive files list
