name: Upload to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate with Google Drive API
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: githubtodrive
        service_account_email: upload@githubtodrive.iam.gserviceaccount.com
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Check if secrets exist
      run: |
        if [ -z "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" ]
        then
          echo "Google Application Credentials not found. Please add them to the repository secrets."
          exit 1
        fi

    - name: Create Google Drive folder
      run: |
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > /tmp/creds.json
        gcloud auth activate-service-account --key-file=/tmp/creds.json
        FOLDER_ID=$(gcloud drive folders list --query "name='upload'" --format "value(id)")
        if [ -z "$FOLDER_ID" ]
        then
          FOLDER_ID=$(gcloud drive folders create "upload" --format "value(id)")
        fi
        echo "Folder ID: $FOLDER_ID"

    - name: Upload files to Google Drive
      run: |
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > /tmp/creds.json
        gcloud auth activate-service-account --key-file=/tmp/creds.json
        for file in upload/*; do
          filename=$(basename "$file")
          gcloud drive files create --parents $FOLDER_ID "$file" --name "$filename"
        done
